package HellApp;


/**
* HellApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* Monday, October 25, 2021 2:58:38 PM CEST
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
